### ISSUE TITLE
read_next_header2() takes long time for closing archive in solid 7z archive when last file is big

### ISSUE THREAD

**Issue by ganego** [Changaco/python-libarchive-c#106]
### Situation (simplified):
- A solid 7z archive with two files that are in different blocks of the solid archive. Second file should be quite large to see the effect.
- Retrieve the data for the first file.

### Problem:
- Script will take a long time to close the the archive when calling `r = read_next_header2(archive_p, entry_p)`.

### Replicate:
- Make a solid 7z archive with:
  - a text file `a.txt` and a bit of text in it (few KB)
  - a big file 200 MB (or more depends on your disk speed - compressing should take like 5s or more) that is not compressible very well, like a video file or so. It has to be alphabetically after a.txt, so for example b.mp4.
- Check 7z file with 7z to make sure it has the .txt in block 0 and the other data in block 1 (visible directly in 7z file manager).
- Run code:

### Code:
```python
import os
os.environ["LIBARCHIVE"] = r"path to archive.dll"
import libarchive


def main():
    with libarchive.file_reader(r"archive.7z") as e:
        for entry in e:
            if entry.isfile:
                print(entry)
                if entry.pathname.lower().endswith(".txt"):
                    data = b"".join(list(entry.get_blocks()))
                else:
                    print("wrong file")


if __name__ == '__main__':
    main()
```

### What will happen:
- Script will instantly print 
```
a.txt
test.mp4
wrong file
```

then it will linger for a couple of seconds and then close the archive. Putting a breakpoint on the `print("wrong file")` and stepping into, will reveal that the script halts at `r = read_next_header2(archive_p, entry_p)`.

Similar behavior cannot be observed when extracting the .txt file with other programs like 7z itself.

With a reversed order of files (z.txt & a.mp4) the problem does not appear.

**Comment by Changaco** [comment]
`read_next_header2` is a libarchive function, so you should [report this issue upstream](https://github.com/libarchive/libarchive/issues).
