### ISSUE TITLE
Different mtime returned in different locales

### ISSUE THREAD

**Issue by pombredanne** [Changaco/python-libarchive-c#13]
See https://travis-ci.org/Changaco/python-libarchive-c/jobs/61875668#L832
The mtime returned is not the same on my machine as it is on the travis slave.
I would expect it to be UTC time or to honor some TZ env var.

**Comment by pombredanne** [comment]
`os.environ['TZ'] = 'UTC'` solves this nicely

**Comment by Changaco** [comment]
That's an upstream issue, we return the value we get from libarchive without modifying it.
