### ISSUE TITLE
Inconsistent mode returned across OSes

### ISSUE THREAD

**Issue by pombredanne** [Changaco/python-libarchive-c#14]
See https://travis-ci.org/Changaco/python-libarchive-c/jobs/61875668#L847
Windows libarchive 3.1.2 returns rw-rw-rw- and Linux Ubuntu 12.x (though this is libarchive12) returns rwxrwxrwx
This could be either :
 * a bug in the binding code
 * a bug in upstream any version
 * a bug in libarchive12

**Comment by Changaco** [comment]
Looks like it was a bug in libarchive12.
