### ISSUE TITLE
Provide actual error details

### ISSUE THREAD

**Issue by pombredanne** [Changaco/python-libarchive-c#18]
Most ffi functions do not have an error check
As a result, it is hard to investigate errors. There should be an error check for every function and appropriate exceptions raised as a needed using the actual message provided by libarchive.

To understand why read: 
https://github.com/libarchive/libarchive/issues/459#issuecomment-91882353
and https://github.com/libarchive/libarchive/issues/538#issuecomment-101184878

I should not have needed to actually write C code to find a bug as part of #9 . If I had an exception returned with the error message from libarchive, I would have found the solution in a snap to the problem of empty pathname.

**Comment by pombredanne** [comment]
Note that in this case neither PyEasyArchive nor python-libarchive were behaving any better and were failing the same as in #9

**Comment by Changaco** [comment]
> Most ffi functions do not have an error check

That's simply not true.

> I should not have needed to actually write C code

You didn't have to, you could have done the same thing in python.

> If I had an exception returned with the error message from libarchive

We don't raise an exception when libarchive returns a warning, we simply log the message.
