### ISSUE TITLE
Append to a new archive

### ISSUE THREAD

**Issue by davinerd** [Changaco/python-libarchive-c#21]
Hello,
I'm trying to append files to a newly created archive.
I've a list of files to append to a new archive, created with `tempfile.NamedTemporaryFile()`. 
Using `libarchive.file_writer`, the archive ended up with only the last file on the list.

Using `libarchive.fd_writer`, the archive has only the first file on the list.

Here are the PoCs:

```python
files = ['a', 'b', 'c', 'd']
tmpArchive = tempfile.NamedTemporaryFile()

for f in files:
    if someCheks(f):
        with libarchive.file_writer(tmpArchive, 'gnutar', 'xz') as archive:
            archive.add_files(f)
```
and

```python
files = ['a', 'b', 'c', 'd']
tmpArchive = tempfile.NamedTemporaryFile()
tmpArchiveFd = tmpArchive.fileno()

for f in files:
    if someCheks(f):
        with libarchive.fd_writer(tmpArchiveFd, 'gnutar', 'xz') as archive:
            archive.add_files(f)
```
Not sure if it's related, but at the end of the loop, I'm doing something like:

```python
with open(tmpArchive.name, 'r+b') as f:
            ret = f.read()
            f.close()

return ret
```
since I need the buffer/data/content.

**Comment by Changaco** [comment]
You simply need to put the `with` outside the loop instead of inside:

```python
files = ['a', 'b', 'c', 'd']
tmpArchive = tempfile.NamedTemporaryFile()

with libarchive.file_writer(tmpArchive, 'gnutar', 'xz') as archive:
    for f in files:
        if someCheks(f):
            archive.add_files(f)
```

**Comment by davinerd** [comment]
Yes, was that simple. It works.

Thank you
