### ISSUE TITLE
Adding file to archive with absolute path

### ISSUE THREAD

**Issue by davinerd** [Changaco/python-libarchive-c#22]
Hello,
I'm in a situation which I have to add files to an archive with absolute path.
Example:

I've `tmpDir` which contains `usr/local/bin/a.bin`, `usr/share/doc/etc.txt`, so the full path is `tmpDir/usr/local/bin/a.bin`, etc etc.

My goal is to add the file to the archive with the path `/usr/local/bin/a.bin`, etc.

I'm able to add the files as `./usr/local/bin/a.bin` (note the dot at the beginning of the string), but when I extract the files it extracts them to the current folder, not to the absolute path.

Here's the actual code:
```
with libarchive.file_writer(tmpArchive.name, format, filter) as archive:
            for dirname, dirnames, filenames in os.walk(tmpDir):
                dirz = dirname.replace(tmpDir, ".")
                for f in filenames:
                    fn = os.path.join(dirz, f)
                    with in_dir(tmpDir):
                        archive.add_files(fn)
```
I've tried modifing the entry.path inside the archive, and of course it doesn't work.
Thanks

**Comment by Changaco** [comment]
I think using absolute paths in archives is considered bad practice. If you want to extract at the root you can tell the extractor to do so.

**Comment by davinerd** [comment]
It's not a thing I can do. I'm creating a deb archive programmaticaly, so the extractor is dpkg.
There is a way I can tweak your code? I'm digging into it but I've some problems finding out how to do that. Even a quick dirty hack would be appreciated.

Thanks

**Comment by Changaco** [comment]
Well, [`.add_files()` explicitly strips leading slashes](https://github.com/Changaco/python-libarchive-c/blob/2.1/libarchive/write.py#L64), so theoretically if you copied that method and modified it to add a leading slash instead, it should work.

**Comment by davinerd** [comment]
It turned out dpkg is fine, it can handles relative paths and make them absolute, so the problem was elsewhere.
However, following your hint, I was able to make add_files() writing absolue paths by adding a flag and removing the lstrip('/').

Thanks

(feel free to close the issue)
