### ISSUE TITLE
unable to build from github source tarballs

### ISSUE THREAD

**Issue by anthraxx** [Changaco/python-libarchive-c#23]
Hey,

It is not possible to build this project from the github tarballs provided through git tags.

This happens because there is no PKG-INFO file in the repo (and in the tarball there is of cause not .git directory as its not a checkout). This makes it impossible to build from the source tarballs prvided through github.
I would *highly* appreciate it if I could build from this source tarball.
    
    Traceback (most recent call last):
      File "setup.py", line 9, in <module>
        version=get_version(),
      File "/build/python-libarchive-c/src/python-libarchive-c-2.1/version.py", line 29, in get_version
        with open(join(d, 'PKG-INFO')) as f:
    IOError: [Errno 2] No such file or directory: '/build/python-libarchive-c/src/python-libarchive-c-2.1/PKG-INFO'

have a nice day,
anthraxx

**Comment by Changaco** [comment]
I'm curious: why do you want to use the GitHub tarballs instead of PyPI?

**Comment by anthraxx** [comment]
because i like to stick as much to the official source as possible, pypi is nice if you want to simply use 'pip' or just run it on your machine... but I plan to package this properly and for that I prefer being as original source near as possible. Also at the end the pypi package does not (always) include everything the source-tree offers (like tests and maybe other meta-data files).

**Comment by Changaco** [comment]
Future git archives of this repository will inject the version number into `version.py`.

**Comment by Changaco** [comment]
Released version 2.2 with this fix.

**Comment by anthraxx** [comment]
@Changaco everything works perfectly, thank you very much!

**Comment by Changaco** [comment]
You're welcome. It took me a while to figure out and implement that solution, I've moved `version.py` into [its own repo](https://github.com/Changaco/version.py) and updated my other python libs.

**Comment by anthraxx** [comment]
@Changaco that looks fancy, good job :+1:
