### ISSUE TITLE
How to construct an archive entry from scratch?

### ISSUE THREAD

**Issue by simon-budig** [Changaco/python-libarchive-c#26]
For some purposes it is useful to create an archive entry from scratch - e.g. device files for a linux root filesystem archive.

It seems that the necessary functions are not mapped with python-libarchive-c: From the examples and from reading the source it is unclear to me how to e.g. set the filename or the data for an entry not read from an existing archive.

If I failed to spot that this becomes a request for better documentation  :)

Thanks,
        Simon

**Comment by Changaco** [comment]
There's a `new_archive_entry` context manager in the `libarchive.entry` module, that may be what you're looking for.

**Comment by Changaco** [comment]
If you need functions that haven't been mapped, you can easily add them by calling the `ffi()` function from `libarchive.ffi`.
