### ISSUE TITLE
missing git release tag for 2.3

### ISSUE THREAD

**Issue by anthraxx** [Changaco/python-libarchive-c#27]
Hi, I have noticed that pypi contains a 2.3 version but there was no git tag for 2.3 published. I'm the maintainer for a distribution and keeping my watch on git tags (which is lot more convenient). Also it would be nice to always have the git tags (and therefor git source tarballs on github) in sync with all released versions :smile: 

hope to see a tag fast,
cheers

**Comment by Changaco** [comment]
Sorry, I'd forgotten to push the tag to GitHub.
