### ISSUE TITLE
consider adding LICENSE or COPYING file to the repository

### ISSUE THREAD

**Issue by anthraxx** [Changaco/python-libarchive-c#28]
Hi, I'm a package maintainer for a distribution of your great library. I would like to ask if its possible to add a LICENSE or COPYING file to the root of this project (which is very very common). This would be great so me and other maintainers may put the license besides the released version.

cheers and thanks for consideration

**Comment by Changaco** [comment]
Already discussed (#7, #24, #25), not gonna happen.
