### ISSUE TITLE
Support a configurable way to load libarchive

### ISSUE THREAD

**Issue by pombreda** [Changaco/python-libarchive-c#3]
The built-in ctypes functions can fall short to find libarchive consistently if this is not in canonical locations
It would be great to have a way to pass well known paths to installed libarchives rather than having the _LIB_FILEPATH and ctypes.cdll.LoadLibrary created/called at import time which makes it rather hard to monkey patch.

**Comment by pombredanne** [comment]
This is excellent and much better and simpler than anything I was thinking about.
Thx!
