### ISSUE TITLE
file permissions issue

### ISSUE THREAD

**Issue by 0-wiz-0** [Changaco/python-libarchive-c#30]
With the 2.3 tarball from pypi, the file permissions of the files in site-packages/libarchive_c-2.3-py3.5.egg-info/* are incorrect (600), which breaks installation of packages which want to use this but are not run by root.
I'm not sure where these permissions come from.
It was the same with 2.2.

**Comment by Changaco** [comment]
I'm the one who created the package, and my `umask` is `066`, so that's where the `600` permissions come from. The question is: what's the best way to fix your problem?

**Comment by 0-wiz-0** [comment]
I don't know the exact process how you create these, but I hope you call a script or python setup target. Can you add a umask call somewhere there?

**Comment by Changaco** [comment]
Good idea, an `os.umask(2)` call in `setup.py` might do the trick.

**Comment by Changaco** [comment]
Changing the `umask` isn't enough, we need to change the permissions of all source files in the git repo because `setuptools` uses hard links when it creates tarballs.

**Comment by Changaco** [comment]
To clarify, permissions are fine in git, they're just wrong in my local copy.

**Comment by Changaco** [comment]
2.4 release with correct permissions uploaded to PyPI.

**Comment by anthraxx** [comment]
hm this umask changes resulted in python setup.py install creating the /usr/lib/python2.7/site-packages/ directory with permissions ``775`` instead of ``755`` making in group writable. This is not really optimal for distribution level of packaging as the directory permissions differ from the global expected values.
in my opinion having that umask in the setup.py is not really optimal and i needed to patch it away to create packages for the distribution that can be shipped

**Comment by 0-wiz-0** [comment]
Why not use the proper umask (octal 022) instead, then?

**Comment by Changaco** [comment]
*sigh*, you're right I should have used 022, matching the `u=rwX,g=rX,o=rX` I put in the `Makefile`. I don't think it's worth another release though.

**Comment by anthraxx** [comment]
well, fair enough... it think that will work :smile_cat: 
No, I assume most package maintainers that care will notice that themselves, from my point of view its perfectly fine if it only gets into the next release! Thank you very much for fixing my concern!
have a nice day :+1:
