### ISSUE TITLE
Add tox support

### ISSUE THREAD

**Issue by krzysztofzuraw** [Changaco/python-libarchive-c#39]
I noticed that in `travis.yml` tests are run 'manually'. I propose to add [tox](https://tox.readthedocs.io/en/latest/). In my local instance I use following tox.ini:
```
[tox]
envlist=py27,py34

[testenv]
install_command=pip install {opts} {packages}
commands=
    py.test -v --color=yes --cov=libarchive --cov-config .coveragerc --cov-report term-missing {toxinidir}/tests {posargs}
deps=
    pytest
    pytest-cov
    six
```

**Comment by Changaco** [comment]
I've recently started using tox as well. Feel free to make a PR, I've added you as a collaborator in this repo so that you can create branches here instead of in a fork.
