### ISSUE TITLE
License audit - GPL2->LGPL2->CC0

### ISSUE THREAD

**Issue by minfrin** [Changaco/python-libarchive-c#45]
While auditing the license changes that have occurred, we have come across some inconsistencies that need to be resolved.

- python-libarchive-c began life as https://github.com/dsoprea/PyEasyArchive, which was licensed GLP2 by the author of PyEasyArchive, dsoprea. The GPL2 license was added to python-libarchive-c by dsoprea here: https://github.com/Changaco/python-libarchive-c/commit/55235ba4472253886c905313573279dec009c429

- The GPL2 license was removed from python-libarchive-c in commit https://github.com/Changaco/python-libarchive-c/commit/7913bbadda8a99aed52881130c06aae4d4d40568 by Changaco, who was not the original author of the code, and was not authorised by the GPL2 to do so. At this point, python-libarchive-c was being distributed in violation of the GPL.

- This problem was brought to the attention of the python-libarchive-c project in the issue https://github.com/Changaco/python-libarchive-c/issues/7, and an attempt was made to solve the issue with https://github.com/Changaco/python-libarchive-c/pull/24, where Changaco switched licenses from the GPL2 to the LGPL2, and then immediately changing the licence to CC0.

- At the time of the license change, Changaco was not the copyright holder of the code, that was held by dsoprea. Section 2(b) of GPL2 states: "You must cause any work that you distribute or publish, that in whole or in part contains or is derived from the Program or any part thereof, to be licensed as a whole at no charge to all third parties under the terms of this License.". Given that Changaco's rights to the code were limited to those limited by GPL2, Changaco was not allowed to change the license to LGPL2, or to CC0. After https://github.com/Changaco/python-libarchive-c/commit/7913bbadda8a99aed52881130c06aae4d4d40568, any users of this library are no longer license compliant.

To fix this, the copyright holder https://github.com/dsoprea needs to authorise the license change made in https://github.com/Changaco/python-libarchive-c/commit/7913bbadda8a99aed52881130c06aae4d4d40568 and then in https://github.com/Changaco/python-libarchive-c/commit/2a6207dd36e095436290bcd528d55beaf77c724c.

**Comment by Changaco** [comment]
You're wasting everyone's time, and you're not even getting the facts right. I didn't change the license of dsoprea's code, it's my own code that I put under LGPL. Then the license was changed to CC0 in #25 with the consent of the other person who had contributed to it.

**Comment by minfrin** [comment]
To leave no room for doubt, can you confirm that all code prior to https://github.com/Changaco/python-libarchive-c/commit/697760556ab99997e7ec5d64386b3bd8c4c3dcf8 and https://github.com/Changaco/python-libarchive-c/commit/a15aebd4d22761da152716988f18c0697ed6b5de was removed and replaced with your code?

Unfortunately your commit messages of "rewrite FFI declarations" and "remove useless or obsolete files" did not make it clear that you had deleted all the existing code. Ideally the deletion should have occurred explicitly to make it clear that project had a clean slate.

**Comment by dsoprea** [comment]
Licensing doesn't work this way, @Changaco. You can't just copy someone else's project (whose history is totally on the record, by the way), remove the licensing, and and say "There's no licensing!".

The good news is that, as Python code, it can be dynamically pulled-down during the install. As long as this is done at the target site and not actually delivered complete *to* the target site, you won't have a problem unless you're dealing with an anal/purest legal team.

**Comment by Changaco** [comment]
@dsoprea If you think you still have a copyright claim feel free to "authorise the license change" like @minfrin suggested above. As far as I'm concerned everything has been rewritten and you have no legal claim.

**Comment by pombredanne** [comment]
From the look of it, this sounds like a complete rewrite, based on the attached clonedigger report but I may be missing something.

[clonedigger.pdf](https://github.com/Changaco/python-libarchive-c/files/619559/clonedigger.pdf)

**Comment by dsoprea** [comment]
It doesn't really make sense to me that you keep my repository, change all
of the code to your own, and then show utter surprise when it's interpreted
to still be mine (because my name is all over it). One might assume that
you rewrote it for legal separation but you did it in the most legally
ambiguous/complicated way.

I will legally continue to have a very solid claim until you start from a
vanilla version-control repository.

Drop the attitude. Welcome to open-source. We're all here to do great
things and there's no room for your ego when you don't understand the
process.

**Comment by pombredanne** [comment]
@Changaco I reopened this because I feel that @dsoprea and @minfrin brought valid points and I can see no obvious reason to dismiss the discussion abruptly, would you agree on this?

**Comment by Changaco** [comment]
I like preserving git histories, but since it's such a problem I can rebase @dsoprea's old commits out of this repo. Would that satisfy everyone?

(@pombredanne It was fine to reopen.)

**Comment by dsoprea** [comment]
Go for it.


Dustin

**Comment by minfrin** [comment]
+1, would make things clear.

**Comment by Changaco** [comment]
Done.
