### ISSUE TITLE
Add convenience functions for file types, similar to the std lib tarfile.tarinfo

### ISSUE THREAD

**Issue by pombreda** [Changaco/python-libarchive-c#5]
It would be great to have convenience functions like in the std lib tarfile.tarinfo for file types rather than to handle flags:
See https://hg.python.org/cpython/file/192f9efe4a38/Lib/tarfile.py#l1459

**Comment by pombreda** [comment]
thanks though for code clarity I would have kept the type constants

**Comment by Changaco** [comment]
I realized that these constants are already defined in the stdlib `stat` module, so I dropped them from `ffi.py`, and I inlined them in `entry.py` instead of importing them because it avoids two dict lookups in each function.

**Comment by pombreda** [comment]
@Changaco your call. I tend to prefer things a bit more explicit with names. Magic numbers are hard to figure out later when you come back to the code. The few dict lookups are likely a non issue compared to the disk IOs going on. And FWIW, libarchive defines these constants explicitly because their definition is not universal (and I recall seeing some comment in the code explaining why they are doing so)
