### ISSUE TITLE
Unable to read 7zip file

### ISSUE THREAD

**Issue by leblancfg** [Changaco/python-libarchive-c#66]
Using the same syntax as the example in your README,

    with libarchive.file_reader('lpr_000b16a_e.7z') as archive:

I get:

    ArchiveError: LZMA codec is unsupported (errno=-1, retcode=-30, archive_p=107949936)

I don't think this gets coverage in the tests, either. If the situation is indeed not platform-specific, updating the README.md would at least be needed.

---

* libarchive version: 3.3.2
* python-libarchive-c version: 2.7
* OS: Windows 7
* Python: 3.6
* 7-zip version: 16.04  `# From which test file was created`

**Comment by Changaco** [comment]
Closing because this is a libarchive problem. Someone else has encountered it and reported it upstream: <https://github.com/libarchive/libarchive/issues/1406>.
