### ISSUE TITLE
Add text of the LGPL to the dist

### ISSUE THREAD

**Issue by pombreda** [Changaco/python-libarchive-c#7]
The license requires users to distribute it together with the code. It would make it easier to include the text (in the sdist and the wheel) so that everyone can comply with zero effort.

**Comment by Changaco** [comment]
I'm not a fan of having the full license text everywhere, it's just a waste of space.

**Comment by pombreda** [comment]
I completely agree by this is a requirement of the LGPL to have the text accompany the redistribution.
As the upstream author you are not obligated to provide the text, but any downstream user would be obliged to whether or not you provide it. By not providing it you let every downstream eventually violate the LGPL terms if they redistribute and an LGPL violation means that they stop to be licensed immediately ... I am not sure that this is what you would want?

This is all weird legalese but these are in the LGPL 2.0 terms.

Noe that if the text size is a concern there are shorter licenses like the MIT ;)
/IANAL-TINLA

**Comment by pombreda** [comment]
Adding some data. 
Section 1 of the LGPL 2.0 at https://www.gnu.org/licenses/old-licenses/lgpl-2.0.html :

    1. You may copy and distribute verbatim copies of the Library's complete
    source code as you receive it, in any medium, provided that you
    conspicuously and appropriately publish on each copy an appropriate
    copyright notice and disclaimer of warranty; keep intact all the notices
    that refer to this License and to the absence of any warranty; and
    distribute a copy of this License along with the Library.

Note: `[...] and distribute a copy of this License along with the Library.`

And in Section 8:

    8. You may not copy, modify, sublicense, link with, or distribute the
    Library except as expressly provided under this License. Any attempt
    otherwise to copy, modify, sublicense, link with, or distribute the
    Library is void, and will automatically terminate your rights under this
    License. However, parties who have received copies, or rights, from you
    under this License will not have their licenses terminated so long as
    such parties remain in full compliance.

Note : `[...] will automatically terminate your rights under this License.`

So the way I read this is that: 1. a redistribution without license text is non-compliant and 2. being non-compliant automatically and immediately terminates the LGPL-2.0 rights for the redistributor.

So stated another way: someone gives a copy of this library to someone else and if this copy did not come with the LGPL text, their license to this library terminates immediately ...
