### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by mingwandroid** [Changaco/python-libarchive-c#71]
Hi, thanks for this really useful wrapper.

I was wondering when the next release is planned. There's been a least one important security related patch that I would love to see in an official release: https://github.com/Changaco/python-libarchive-c/commit/4784e43a9ca7835cdfbceba718a527e1f8033447

**Comment by Changaco** [comment]
https://github.com/Changaco/python-libarchive-c/releases/tag/2.8
