### ISSUE TITLE
Keeping an archive open without using a context generator?

### ISSUE THREAD

**Issue by mingwandroid** [Changaco/python-libarchive-c#76]
Hi,

First, thanks for all of your work on this project.

I have an existing codebase in which I want to use python-libarchive-c. The code isn't structured to allow using generators, being based around the tarfile module originally.

I managed to hack up a way to get what I want (criticism very welcome!) 

It requires exporting ArchiveWrite from libarchive/__init__.py. Then in your own code you can do the following:

```
class NewArchiveWrite(libarchive.ArchiveWrite):
    def __init__(self, filename, format_name, filter_name=None, options=''):
        from libarchive import ffi
        self.filename = filename
        self.archive_p = ffi.write_new()
        libarchive.ArchiveWrite.__init__(self, self.archive_p)
        getattr(ffi, 'write_set_format_' + format_name)(self.archive_p)
        if filter_name:
            getattr(ffi, 'write_add_filter_' + filter_name)(self.archive_p)
        if options:
            if not isinstance(options, bytes):
                options = options.encode('utf-8')
            ffi.write_set_options(self.archive_p, options)
        ffi.write_open_filename_w(self.archive_p, self.filename)

    def __del__(self):
        from libarchive import ffi
        ffi.write_close(self.archive_p)
        ffi.write_free(self.archive_p)
```

.. then use this class. What do you think? Would a PR to export ArchiveWrite be acceptable? Is there a better way to achieve what I want?

**Comment by Changaco** [comment]
I don't see why you want to import the `ArchiveWrite` class from the top module, what's wrong with `from liberapay.write import ArchiveWrite`?

P.S. Using `__del__` is probably not a good idea, see the warning in [the official documentation](https://docs.python.org/3/reference/datamodel.html#object.__del__).

**Comment by mingwandroid** [comment]
Works for me, thanks for your help!
