### ISSUE TITLE
Adding LICENSE.md to MANIFEST.in

### ISSUE THREAD

**Issue by jakirkham** [Changaco/python-libarchive-c#78]
Would be nice to include `LICENSE.md` to `MANIFEST.in` so that the license file ships with `sdist`s and other packages. Bonus points if it is added to [`setup.cfg` for wheels]( https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file ).

**Comment by Changaco** [comment]
There is no need to include the LICENSE file in any package, the CC0 doesn't have any "distribute the license with the code" clause. Anyway the LICENSE file only contains a URL and was only created as an experiment to see if GitHub would detect the license.

**Comment by jakirkham** [comment]
It would be nice to include it in any event for users that may be getting the package from third-party repos just so they can verify for themselves the license is something they are comfortable with. Would be happy to send a PR to add this.

**Comment by Changaco** [comment]
This doesn't seem to be necessary anymore. The license file ends up in the archives even without being listed in the manifest.
