### ISSUE TITLE
Ability to decrypt zip and 7z files

### ISSUE THREAD

**Issue by kbalk** [Changaco/python-libarchive-c#87]
Is it possible to decrypt and decompress zip and 7z files?  There is a libarchive function archive_read_add_passphrase(struct archive *_a, const char *passphrase) that allows a caller to provide a password.  Is that something you would consider adding/supporting?

**Comment by ION28** [comment]
The other Python Libarchive project has an open PR that adds encryption support here: https://github.com/dsoprea/PyEasyArchive/pull/34

**Comment by Changaco** [comment]
Done in #109 and released in version 3.0.

**Comment by AngelineNinu** [comment]
Hi everyone,
Does the passphrase you are trying can be non ascii, will we be able to decrypt zip file using it when use this libarry
