### ISSUE TITLE
Extract empty files?

### ISSUE THREAD

**Issue by msarahan** [Changaco/python-libarchive-c#89]
I have a .tar.bz2 file that has empty (zero-length) files in it, like you'd get from just using ``touch`` to create a file.  These are not getting extracted when I use this code to extract the tarball:

```
def _tar_xf(tarball, dir_path):
    flags = libarchive.extract.EXTRACT_TIME | \
            libarchive.extract.EXTRACT_PERM | \
            libarchive.extract.EXTRACT_SECURE_NODOTDOT | \
            libarchive.extract.EXTRACT_SECURE_SYMLINKS | \
            libarchive.extract.EXTRACT_SECURE_NOABSOLUTEPATHS | \
            libarchive.extract.EXTRACT_SPARSE | \
            libarchive.extract.EXTRACT_UNLINK
    if not os.path.isabs(tarball):
        tarball = os.path.join(os.getcwd(), tarball)
    with utils.tmp_chdir(dir_path):
        libarchive.extract_file(tarball, flags)
```

I think it might be because the loop to stream data ends early at https://github.com/Changaco/python-libarchive-c/blob/master/libarchive/extract.py#L55, but in changing that to always call the write function at least once, it still doesn't work.  I've tried to inspect the ``entry`` object, but I don't know how to make sense of it - all the interesting fields, like name and path are just empty.  Do you have any tips for how to debug/improve this issue?  I'd be happy to submit a PR if you point me in the right direction.

**Comment by Changaco** [comment]
I think you should submit a PR that adds a failing test for this issue. That test will confirm the problem and help fix it.

**Comment by msarahan** [comment]
I'm pretty sure this was a bug on my end in the way that I was enumerating which files to include in an archive.  Sorry for the noise on that.
