### ISSUE TITLE
Modifying the path of an entry before adding it to an archive

### ISSUE THREAD

**Issue by achapkowski** [Changaco/python-libarchive-c#93]
How do I write to an archives specific folder?

For example:

```
myfile = r"c:\temp\amazing\location\data.txt"

```

I want this file path to be in my archive as:

**PSEUDO CODE**

```
archive_location = "/data/data.txt"

sd_output = r'c:\temp\amazing\archive.7z'
if os.path.isfile(sd_output):
    os.remove(sd_output)
with libarchive.file_writer(sd_output, '7zip') as archive:
    archive.add_files(myfile, archive_location) # doesn't work
```

Can I specify that?  The documentation seems a bit vague.

Thank you

**Comment by Changaco** [comment]
It can be done with the `add_file_from_memory` method, but we would need a new `add_file` method to make it easier.
