### ISSUE TITLE
Installing python-libarchive using pip via wheel

### ISSUE THREAD

**Issue by odidev** [Changaco/python-libarchive-c#99]
**Summary**
Installing python-libarchive via pip using command "pip3 install python-libarchive" tries to build wheel from source code for any platform.

**Problem description**
Python-libarchive don't have wheel on PyPI repository. So, while installing python-libarchive via pip,  it builds wheel from tar file provided in PyPI which takes more time to install. Making wheel available will benefit users by minimizing installation time.

**Expected Output**
Pip should be able to download python-libarchive wheel from PyPI repository rather than building it from source code.

@Changaco , I was able to build wheel with command "python setup.py bdist_wheel" and libarchive_c-2.9.post3-py2.py3-none-any.whl has been created in dist folder. I have tried installing in both x86 and aarch64 platform with command "pip install libarchive_c-2.9.post3-py2.py3-none-any.whl", it got installed successfully. Please let me know if any help required in building wheel and uploading it to PyPI repository.

**Comment by Changaco** [comment]
You're installing a different module. [libarchive-c](https://pypi.org/project/libarchive-c/) has a wheel, [python-libarchive](https://pypi.org/project/python-libarchive/) doesn't.

```
% pip install libarchive-c
Collecting libarchive-c
  Downloading libarchive_c-2.9-py2.py3-none-any.whl (11 kB)
Installing collected packages: libarchive-c
Successfully installed libarchive-c-2.9
```
